### ISSUE TITLE
homebrew cask?

### ISSUE THREAD

**Issue by AlJohri** [alvesjtiago/airpass#1]
hi @alvesjtiago, it would be great to be able to install this via `brew cask install airpass`. in case you're unfamiliar: https://caskroom.github.io/
and of course, homebrew overall: https://brew.sh/

thanks!

**Comment by alvesjtiago** [comment]
@AlJohri submitted and merged (https://github.com/caskroom/homebrew-cask/pull/46192).

Using the following command you should be able to install Airpass using homebrew cask:
```
brew cask install airpass
```

Hope it helps!
Thank you once again for the suggestion 😊

**Comment by AlJohri** [comment]
thanks @alvesjtiago!
