### ISSUE TITLE
missing script: rebuild

### ISSUE THREAD

**Issue by basarakcin** [alvesjtiago/airpass#2]
rebuild script is missing in package.json. Could not build from source.

**Comment by alvesjtiago** [comment]
Thanks for opening this issue @basarakcin.
I haven't touched this project in over a year so I definitely need to update it and add the necessary scripts. I'll let you know as soon as I do that.

**Comment by alvesjtiago** [comment]
@basarakcin I've just updated the dependencies and removed the rebuild step from the instructions since it seems that it's no longer needed.
I'm closing this issue but please let me know if it doesn't work for you.
